function createtextbox(figure1)
%CREATETEXTBOX(figure1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 06-May-2020 00:47:24

% Create textbox
annotation(figure1,'textbox',...
    [0.0391578947368418 0.748353909465019 0.0461491228070173 0.118312757201646],...
    'String',{'Constant','segment','length=','20'},...
    'FitBoxToText','off');

